In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")

In [4]:
train_data.head(5)

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True

In [6]:
test_data.head(5)

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0013_01      Earth      True  G/3/S  TRAPPIST-1e  27.0  False   
1     0018_01      Earth     False  F/4/S  TRAPPIST-1e  19.0  False   
2     0019_01     Europa      True  C/0/S  55 Cancri e  31.0  False   
3     0021_01     Europa     False  C/1/S  TRAPPIST-1e  38.0  False   
4     0023_01      Earth     False  F/5/S  TRAPPIST-1e  20.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck              Name  
0          0.0        0.0           0.0     0.0     0.0   Nelly Carsoning  
1          0.0        9.0           0.0  2823.0     0.0    Lerome Peckers  
2          0.0        0.0           0.0     0.0     0.0   Sabih Unhearfus  
3          0.0     6652.0           0.0   181.0   585.0  Meratz Caltilter  
4         10.0        0.0         635.0     0.0     0.0   Brence Harperez

In [5]:
print(train_data.shape)
print(test_data.shape)

(8693, 14)
(4277, 13)


In [7]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   8693 non-null   object 
 1   HomePlanet    8492 non-null   object 
 2   CryoSleep     8476 non-null   object 
 3   Cabin         8494 non-null   object 
 4   Destination   8511 non-null   object 
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object 
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object 
 13  Transported   8693 non-null   bool   
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB


In [9]:
test_data.isna().sum()

PassengerId       0
HomePlanet       87
CryoSleep        93
Cabin           100
Destination      92
Age              91
VIP              93
RoomService      82
FoodCourt       106
ShoppingMall     98
Spa             101
VRDeck           80
Name             94
dtype: int64

In [8]:
obj_data = train_data.select_dtypes('object')
for i in obj_data:
    print(train_data[i].name)
    print(train_data[i].unique())

PassengerId
['0001_01' '0002_01' '0003_01' ... '9279_01' '9280_01' '9280_02']
HomePlanet
['Europa' 'Earth' 'Mars' nan]
CryoSleep
[False True nan]
Cabin
['B/0/P' 'F/0/S' 'A/0/S' ... 'G/1499/S' 'G/1500/S' 'E/608/S']
Destination
['TRAPPIST-1e' 'PSO J318.5-22' '55 Cancri e' nan]
VIP
[False True nan]
Name
['Maham Ofracculy' 'Juanna Vines' 'Altark Susent' ... 'Fayey Connon'
 'Celeon Hontichre' 'Propsh Hontichre']


In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

col = ['HomePlanet','CryoSleep','Destination','VIP']

for i in col:
    train_data[i]=le.fit_transform(train_data[i])
    test_data[i]=le.fit_transform(test_data[i])

In [12]:
train_data = train_data.select_dtypes(['bool', 'float64', 'int32'])
test_data = test_data.select_dtypes(['float64', 'int32'])
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   HomePlanet    8693 non-null   int32  
 1   CryoSleep     8693 non-null   int32  
 2   Destination   8693 non-null   int32  
 3   Age           8514 non-null   float64
 4   VIP           8693 non-null   int32  
 5   RoomService   8512 non-null   float64
 6   FoodCourt     8510 non-null   float64
 7   ShoppingMall  8485 non-null   float64
 8   Spa           8510 non-null   float64
 9   VRDeck        8505 non-null   float64
 10  Transported   8693 non-null   bool   
dtypes: bool(1), float64(6), int32(4)
memory usage: 551.9 KB


In [13]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   HomePlanet    4277 non-null   int32  
 1   CryoSleep     4277 non-null   int32  
 2   Destination   4277 non-null   int32  
 3   Age           4186 non-null   float64
 4   VIP           4277 non-null   int32  
 5   RoomService   4195 non-null   float64
 6   FoodCourt     4171 non-null   float64
 7   ShoppingMall  4179 non-null   float64
 8   Spa           4176 non-null   float64
 9   VRDeck        4197 non-null   float64
dtypes: float64(6), int32(4)
memory usage: 267.4 KB


In [14]:
train_data.corr()

HomePlanet  CryoSleep  Destination       Age       VIP  \
HomePlanet      1.000000   0.068726     0.042618  0.124376  0.044255   
CryoSleep       0.068726   1.000000    -0.085571 -0.069141 -0.023407   
Destination     0.042618  -0.085571     1.000000 -0.004248 -0.024905   
Age             0.124376  -0.069141    -0.004248  1.000000  0.032874   
VIP             0.044255  -0.023407    -0.024905  0.032874  1.000000   
RoomService     0.194435  -0.219033     0.044733  0.068723  0.038368   
FoodCourt       0.056788  -0.183855    -0.110659  0.130421  0.055531   
ShoppingMall    0.090020  -0.189642     0.022977  0.033133 -0.009756   
Spa             0.045538  -0.180362    -0.053614  0.123970  0.019832   
VRDeck          0.035397  -0.173856    -0.073654  0.101007  0.054235   
Transported     0.107755   0.404716    -0.104817 -0.075026 -0.014260   

              RoomService  FoodCourt  ShoppingMall       Spa    VRDeck  \
HomePlanet       0.194435   0.056788      0.090020  0.045538  0.035397   
CryoSleep       -0.219033  -0.183855     -0.189642 -0.180362 -0.173856   
Destination      0.044733  -0.110659      0.022977 -0.053614 -0.073654   
Age              0.068723   0.130421      0.033133  0.123970  0.101007   
VIP              0.038368   0.055531     -0.009756  0.019832  0.054235   
RoomService      1.000000  -0.015889      0.054480  0.010080 -0.019581   
FoodCourt       -0.015889   1.000000     -0.014228  0.221891  0.227995   
ShoppingMall     0.054480  -0.014228      1.000000  0.013879 -0.007322   
Spa              0.010080   0.221891      0.013879  1.000000  0.153821   
VRDeck          -0.019581   0.227995     -0.007322  0.153821  1.000000   
Transported     -0.244611   0.046566      0.010141 -0.221131 -0.207075   

              Transported  
HomePlanet       0.107755  
CryoSleep        0.404716  
Destination     -0.104817  
Age             -0.075026  
VIP             -0.014260  
RoomService     -0.244611  
FoodCourt        0.046566  
ShoppingMall     0.010141  
Spa             -0.221131  
VRDeck          -0.207075  
Transported      1.000000

In [15]:
train_data.drop(['Age','VIP','ShoppingMall'],axis=1,inplace=True)
test_data.drop(['Age','VIP','ShoppingMall'],axis=1,inplace=True)

In [16]:
train_data.head()

HomePlanet  CryoSleep  Destination  RoomService  FoodCourt     Spa  VRDeck  \
0           1          0            2          0.0        0.0     0.0     0.0   
1           0          0            2        109.0        9.0   549.0    44.0   
2           1          0            2         43.0     3576.0  6715.0    49.0   
3           1          0            2          0.0     1283.0  3329.0   193.0   
4           0          0            2        303.0       70.0   565.0     2.0   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True

In [17]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   HomePlanet   8693 non-null   int32  
 1   CryoSleep    8693 non-null   int32  
 2   Destination  8693 non-null   int32  
 3   RoomService  8512 non-null   float64
 4   FoodCourt    8510 non-null   float64
 5   Spa          8510 non-null   float64
 6   VRDeck       8505 non-null   float64
 7   Transported  8693 non-null   bool   
dtypes: bool(1), float64(4), int32(3)
memory usage: 382.1 KB


In [18]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   HomePlanet   4277 non-null   int32  
 1   CryoSleep    4277 non-null   int32  
 2   Destination  4277 non-null   int32  
 3   RoomService  4195 non-null   float64
 4   FoodCourt    4171 non-null   float64
 5   Spa          4176 non-null   float64
 6   VRDeck       4197 non-null   float64
dtypes: float64(4), int32(3)
memory usage: 183.9 KB


In [21]:
fill_data = train_data.select_dtypes('float64')

In [22]:
for i in fill_data:
    train_data[i].fillna(value=train_data[i].mean(), inplace=True)
    test_data[i].fillna(value=test_data[i].mean(), inplace=True)

In [24]:
train_data.isna().sum()

HomePlanet     0
CryoSleep      0
Destination    0
RoomService    0
FoodCourt      0
Spa            0
VRDeck         0
Transported    0
dtype: int64

In [25]:
x = train_data.drop('Transported', axis=1)
y = train_data['Transported']

In [28]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [29]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [31]:
rfc = RandomForestClassifier()
dtc = DecisionTreeClassifier()

In [32]:
rfc.fit(x_train, y_train)
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [33]:
rfc.score(x_test, y_test)

0.7832087406555491

In [34]:
dtc.score(x_test, y_test)

0.7406555491661875

In [36]:
y_pred = rfc.predict(x_test)
y_pred[:10]

array([False,  True, False, False,  True, False, False,  True,  True,
       False])

In [37]:
from sklearn.metrics import classification_report, confusion_matrix

In [38]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.81      0.73      0.77       863
        True       0.76      0.83      0.79       876

    accuracy                           0.78      1739
   macro avg       0.79      0.78      0.78      1739
weighted avg       0.79      0.78      0.78      1739



In [39]:
print(confusion_matrix(y_test, y_pred))

[[632 231]
 [146 730]]


In [40]:
test_predict = rfc.predict(test_data)

In [41]:
test_predict

array([ True, False,  True, ...,  True,  True,  True])

In [44]:
df = pd.read_csv('test.csv')

In [45]:
df["Transported"] = test_predict

csv = df[['PassengerId',"Transported"]]

csv.to_csv("submission.csv", index = False)